CREATE DATABASE CLASSWORK;
USE CLASSWORK;
CREATE TABLE DEPARTMENTS(DEPT_ID INT PRIMARY KEY auto_increment,DEPT_NAME VARCHAR(50));

INSERT INTO DEPARTMENTS(DEPT_ID,DEPT_NAME)values(1,"HR");
INSERT INTO DEPARTMENTS(DEPT_ID,DEPT_NAME)values(2,"IT");
INSERT INTO DEPARTMENTS(DEPT_ID,DEPT_NAME)values(3,"FINANCE");

CREATE TABLE EMPLOYEE(EMP_ID INT PRIMARY KEY auto_increment,EMP_NAME VARCHAR(20),SALARY INT , DEPT_ID INT ,
foreign key(DEPT_ID) references DEPARTMENTS(DEPT_ID),
 JOINDATE DATE);

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,SALARY,DEPT_ID,JOINDATE)VALUES('101','ALICE','75000','2','2022-04-10');
INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,SALARY,DEPT_ID,JOINDATE)VALUES('102','BOB','60000','1','2019-12-20');
INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,SALARY,DEPT_ID,JOINDATE)VALUES('103','CHARLIE','82000','3','2021-06-15');
INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,SALARY,DEPT_ID,JOINDATE)VALUES('104','DAVID','55000','2','2022-08-05');
INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,SALARY,DEPT_ID,JOINDATE)VALUES('105','EVA','90000','3','2023-02-25');

SELECT EMP_NAME,SALARY FROM EMPLOYEE;
SELECT EMP_NAME FROM EMPLOYEE WHERE SALARY> 60000;
SELECT EMP_NAME FROM EMPLOYEE WHERE JOINDATE > 2021-01-01;
SELECT EMP_NAME FROM EMPLOYEE WHERE DEPT_ID=2;
SELECT EMP_NAME FROM EMPLOYEE WHERE EMP_NAME LIKE 'A%';
UPDATE EMPLOYEE SET DEPT_ID=3 WHERE EMP_NAME= 'BOB';
UPDATE EMPLOYEE SET SALARY  = SALARY+5000 WHERE ID='3';
SELECT EMP_NAME FROM EMPLOYEE WHERE JOINDATE > 2020-01-01;
SELECT * FROM EMPLOYEE WHERE EMP_ID=104;


SELECT sum(SALARY) as total from EMPLOYEE;
SELECT avg(SALARY)  from EMPLOYEE;
SELECT max(SALARY) from EMPLOYEE;
SELECT EMP_NAME,count(*) FROM EMPLOYEE GROUP BY EMP_NAME;
SELECT min(SALARY) FROM EMPLOYEE WHERE DEPT_ID=2;
SELECT DEPT_ID,count(*) FROM EMPLOYEE group by DEPT_ID;
