CREATE DATABASE CLASS2;
USE CLASS2;
CREATE TABLE EMPLOYEE(ID INT PRIMARY KEY auto_increment,FIRST_NAME VARCHAR(25),LAST_NAME VARCHAR(25),EMAIL VARCHAR(100),AGE INT NOT NULL,HIRE_DATE DATE);
DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE(ID INT PRIMARY KEY auto_increment,FIRST_NAME VARCHAR(25),LAST_NAME VARCHAR(25),EMAIL VARCHAR(100),AGE INT NOT NULL,HIRE_DATE DATE);
INSERT INTO  EMPLOYEE (ID, FIRST_NAME,LAST_NAME, EMAIL, AGE,HIRE_DATE)VALUES(1,'JOHN','DOE','jhon@gmail.com',20,'2023-12-31'); 
INSERT INTO  EMPLOYEE (ID, FIRST_NAME,LAST_NAME, EMAIL, AGE,HIRE_DATE)VALUES(2,'HARLIT','MILTON','harlit@gmail.com',21,'2023-12-12'); 
INSERT INTO  EMPLOYEE (ID, FIRST_NAME,LAST_NAME, EMAIL, AGE,HIRE_DATE)VALUES(3,'NEHA','NITHIN','neha@gmail.com',21,'2023-12-10');
INSERT INTO  EMPLOYEE (FIRST_NAME,LAST_NAME, EMAIL, AGE,HIRE_DATE)VALUES('ARCHANA','SHAJI','archana@gmail.com',21,'2023-12-17');  
INSERT INTO  EMPLOYEE (FIRST_NAME,LAST_NAME, EMAIL, AGE,HIRE_DATE)VALUES('ARCHANA','SHAJI','archana@gmail.com',21,'2023-12-17');  
ALTER TABLE EMPLOYEE ADD PHONE_NUMBER VARCHAR(15);
UPDATE EMPLOYEE SET PHONE_NUMBER = 9876543526 WHERE ID = 1;
UPDATE EMPLOYEE SET PHONE_NUMBER = 8975623157 WHERE ID = 2;
DELETE FROM EMPLOYEE WHERE AGE > 24;
USE CLASS2;
DELETE FROM EMPLOYEE WHERE AGE > 24;

