CREATE DATABASE JOINN;
USE JOINN;
CREATE TABLE EMP(
EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
EMP_NAME VARCHAR(30),
DEPT_ID INT, FOREIGN KEY (DEPT_ID) REFERENCES DEPT(DEPT_ID),
SALARY INT);
INSERT INTO EMP(EMP_ID, EMP_NAME, DEPT_ID, SALARY) VALUES (1, "ARUN", 10, 30000);
INSERT INTO EMP(EMP_NAME, DEPT_ID, SALARY) VALUES ("BEENA", 11, 45000);
INSERT INTO EMP(EMP_NAME, DEPT_ID, SALARY) VALUES ("CHARU", 12, 50000);
INSERT INTO EMP(EMP_NAME, DEPT_ID, SALARY) VALUES ("DEEPA", 10, 28000);

CREATE TABLE DEPT(
DEPT_ID INT PRIMARY KEY AUTO_INCREMENT,
DEPT_NAME VARCHAR(30));
INSERT INTO DEPT(DEPT_ID, DEPT_NAME) VALUES (10,"HR");
INSERT INTO DEPT(DEPT_NAME) VALUES ("IT");
INSERT INTO DEPT(DEPT_NAME) VALUES ("FINANCE");

SELECT E.EMP_NAME, D.DEPT_NAME FROM EMP E INNER JOIN DEPT D ON E.DEPT_ID=D.DEPT_ID;
SELECT E.EMP_NAME, D.DEPT_NAME FROM EMP E LEFT JOIN DEPT D ON E.DEPT_ID=D.DEPT_ID;
SELECT E.EMP_NAME, D.DEPT_NAME FROM EMP E RIGHT JOIN DEPT D ON E.DEPT_ID=D.DEPT_ID; -- RIGHT JOIN OR RIGHT OUTER JOIN
-- FULL JOIN
SELECT E.EMP_NAME, D.DEPT_NAME FROM EMP E LEFT JOIN DEPT D ON E.DEPT_ID=D.DEPT_ID
UNION 
SELECT E.EMP_NAME, D.DEPT_NAME FROM EMP E RIGHT JOIN DEPT D ON E.DEPT_ID=D.DEPT_ID;